Fix broken industrial collision detection
ros-industrial-attic/industrial_moveit pull request #77
Opened 2018-09-10 18:02 UTC by jrgnicho

This PR addresses the issue described in #70 where the **industrial_collision_detection** package broke after [changes made to moveit collision library](https://github.com/ros-planning/moveit/issues/488) that introduced the ability to perform distance queries along with some other improvements.  Thus this fix involves the following changes:
- Removed the duplicate Distance query data structures from industrial_collision_detection
- Added rather unpolished implementations of the new purely virtual functions inherited from the CollisionRobot and CollisionWorld interfaces.
- The constrained_ik package no longer depends on **industrial_collision_detection**

As of now the **industrial_collision_detection** package is no longer a dependency to any other package, nevertheless I chose to keep it around just in case.

This PR replaces #71 and #76 

@Levi-Armstrong I had to modify constrained_ik in order for it to build so hopefully I didn't break anything but could you suggest a way to check?

2018-09-11 03:07 UTC, davetcoleman commented
> nevertheless I chose to keep it around just in case.

Does not git history achieve this "just in case" scenario? It seems to me keeping it will only confuse future contributors / developers and cause more maintenance hassle

2018-09-11 03:09 UTC, davetcoleman commented on industrial_collision_detection/src/collision_detection/collision_common.cpp
> +    if (false /*!cdata->req->global*/)
add comment for why you are disabling this

2018-09-11 03:09 UTC, davetcoleman commented on industrial_collision_detection/src/collision_detection/collision_common.cpp
> +      if (false /*!cdata->req->global*/)
same

2018-09-11 15:04 UTC, jrgnicho commented
>Does not git history achieve this "just in case" scenario? It seems to me keeping it will only confuse future contributors / developers and cause more maintenance hassle

@davetcoleman  indeed git does keep the history.  My argument for keeping **industrial_collision_detection** around is that there may be exclusive functionality there that the constrained_ik planner still needs.  I did my best to "upgrade" **constrained_ik** to the new moveit Distance Query Structures but some code didn't directly translate and so I could've broken something and it would be easier to fix/restore if industrial collision detection was kept.
In order to avoid confusing developers we could add a readme explaining this.

2018-09-12 22:26 UTC, jrgnicho commented
@davetcoleman I made the requested changes.

2018-09-12 22:33 UTC, davetcoleman commented
> In order to avoid confusing developers we could add a readme explaining this.

Agreed - can you just copy your explanation in your previous comment into the README?

2018-09-13 15:46 UTC, jrgnicho commented
@davetcoleman a REAME with an explanation of industrial_collision_detection has been added.

2018-09-13 17:50 UTC, davetcoleman approved these changes

2018-09-13 18:18 UTC, Levi-Armstrong requested changes

2018-09-13 18:18 UTC, Levi-Armstrong commented on industrial_collision_detection/src/collision_detection/collision_common.cpp
> +    double d = fcl::distance(o1, o2, fcl::DistanceRequest(), fcl_result);
needs to be fcl::DistanceRequest(cdata->req->enable_nearest_points).

2018-09-13 18:18 UTC, Levi-Armstrong commented on industrial_collision_detection/src/collision_detection/collision_common.cpp
> +    if (false /*!cdata->req->global*/)
cdata->req->type == DistanceRequestType::GLOBAL

2018-09-13 18:18 UTC, Levi-Armstrong commented on industrial_collision_detection/src/collision_detection/collision_common.cpp
> +      if (false /*!cdata->req->global*/)
Same as above

2018-09-13 18:18 UTC, Levi-Armstrong commented on industrial_collision_detection/src/collision_detection/collision_robot_industrial.cpp
>      DistanceResult dres;
add dreq.type == DistanceRequestType::GLOBAL

2018-09-13 18:18 UTC, Levi-Armstrong commented on industrial_collision_detection/src/collision_detection/collision_world_industrial.cpp
>      DistanceResult dres;
add dreq.type == DistanceRequestType::GLOBAL

2018-09-14 15:51 UTC, jrgnicho commented
@Levi-Armstrong I've made the requested changes.

2018-09-16 00:13 UTC, Levi-Armstrong approved these changes

2018-09-17 15:28 UTC, merged